--------------------------------------------------------
--  파일이 생성됨 - 화요일-12월-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MOVIE_TICKETING
--------------------------------------------------------

  CREATE TABLE "BISCUIT"."MOVIE_TICKETING" 
   (	"MOVIE_T_NUM" VARCHAR2(200 BYTE), 
	"ID" VARCHAR2(200 BYTE), 
	"MOVIEINFO_NUM" NUMBER(5,0), 
	"CINEMA_NUM" NUMBER(5,0), 
	"THEATER_NUM" NUMBER(5,0), 
	"SEAT_NAME" VARCHAR2(20 BYTE), 
	"SEAT_CHECK" NUMBER DEFAULT 0, 
	"PRICE" NUMBER(10,0), 
	"BOOK_DATE" DATE, 
	"TIMEINFO_START" VARCHAR2(200 BYTE), 
	"TIMEINFO_DATE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BISCUIT"."MOVIE_TICKETING"."SEAT_CHECK" IS '예매 취소 1
';
REM INSERTING into BISCUIT.MOVIE_TICKETING
SET DEFINE OFF;
Insert into BISCUIT.MOVIE_TICKETING (MOVIE_T_NUM,ID,MOVIEINFO_NUM,CINEMA_NUM,THEATER_NUM,SEAT_NAME,SEAT_CHECK,PRICE,BOOK_DATE,TIMEINFO_START,TIMEINFO_DATE) values ('0101-0270-1400-1225-M700','test',270,1,1,'M7',0,10000,to_date('19/12/23','RR/MM/DD'),'14:00','19/12/25');
Insert into BISCUIT.MOVIE_TICKETING (MOVIE_T_NUM,ID,MOVIEINFO_NUM,CINEMA_NUM,THEATER_NUM,SEAT_NAME,SEAT_CHECK,PRICE,BOOK_DATE,TIMEINFO_START,TIMEINFO_DATE) values ('0101-0270-1400-1225-M800','test',270,1,1,'M8',0,10000,to_date('19/12/23','RR/MM/DD'),'14:00','19/12/25');
Insert into BISCUIT.MOVIE_TICKETING (MOVIE_T_NUM,ID,MOVIEINFO_NUM,CINEMA_NUM,THEATER_NUM,SEAT_NAME,SEAT_CHECK,PRICE,BOOK_DATE,TIMEINFO_START,TIMEINFO_DATE) values ('0101-0270-1400-1225-M900','test',270,1,1,'M9',0,10000,to_date('19/12/23','RR/MM/DD'),'14:00','19/12/25');
Insert into BISCUIT.MOVIE_TICKETING (MOVIE_T_NUM,ID,MOVIEINFO_NUM,CINEMA_NUM,THEATER_NUM,SEAT_NAME,SEAT_CHECK,PRICE,BOOK_DATE,TIMEINFO_START,TIMEINFO_DATE) values ('0101-0270-1400-1225-M101','test',270,1,1,'M10',0,10000,to_date('19/12/23','RR/MM/DD'),'14:00','19/12/25');
Insert into BISCUIT.MOVIE_TICKETING (MOVIE_T_NUM,ID,MOVIEINFO_NUM,CINEMA_NUM,THEATER_NUM,SEAT_NAME,SEAT_CHECK,PRICE,BOOK_DATE,TIMEINFO_START,TIMEINFO_DATE) values ('0101-0270-1400-1225-M110','test',270,1,1,'M11',0,10000,to_date('19/12/23','RR/MM/DD'),'14:00','19/12/25');
--------------------------------------------------------
--  DDL for Index MOVIET_MOVIETNUM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BISCUIT"."MOVIET_MOVIETNUM_PK" ON "BISCUIT"."MOVIE_TICKETING" ("MOVIE_T_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MOVIE_TICKETING
--------------------------------------------------------

  ALTER TABLE "BISCUIT"."MOVIE_TICKETING" ADD CONSTRAINT "MOVIET_MOVIETNUM_PK" PRIMARY KEY ("MOVIE_T_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BISCUIT"."MOVIE_TICKETING" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MOVIE_TICKETING
--------------------------------------------------------

  ALTER TABLE "BISCUIT"."MOVIE_TICKETING" ADD CONSTRAINT "MOVIET_CINEMANUM_FK" FOREIGN KEY ("CINEMA_NUM")
	  REFERENCES "BISCUIT"."CINEMA" ("CINEMA_NUM") ENABLE;
  ALTER TABLE "BISCUIT"."MOVIE_TICKETING" ADD CONSTRAINT "MOVIET_MOVIEINFONUM_FK" FOREIGN KEY ("MOVIEINFO_NUM")
	  REFERENCES "BISCUIT"."MOVIEINFO" ("MOVIEINFO_NUM") ENABLE;
  ALTER TABLE "BISCUIT"."MOVIE_TICKETING" ADD CONSTRAINT "MOVIET_THEATERNUM_FK" FOREIGN KEY ("THEATER_NUM")
	  REFERENCES "BISCUIT"."THEATER" ("THEATER_NUM") ENABLE;
