--------------------------------------------------------
--  ∆ƒ¿œ¿Ã ª˝º∫µ  - »≠ø‰¿œ-12ø˘-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STORE
--------------------------------------------------------

  CREATE TABLE "BISCUIT"."STORE" 
   (	"STORE_NUM" NUMBER(5,0), 
	"STORE_NAME" VARCHAR2(200 BYTE), 
	"STORE_PRICE" NUMBER(8,0), 
	"STORE_SALE" NUMBER(8,0) DEFAULT 0, 
	"STORE_NOTE" VARCHAR2(400 BYTE), 
	"STORE_PACKAGE" NUMBER(1,0) DEFAULT 1, 
	"STORE_IMG" VARCHAR2(200 BYTE), 
	"STORE_THUMBIMG" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BISCUIT.STORE
SET DEFINE OFF;
Insert into BISCUIT.STORE (STORE_NUM,STORE_NAME,STORE_PRICE,STORE_SALE,STORE_NOTE,STORE_PACKAGE,STORE_IMG,STORE_THUMBIMG) values (54,'¥ı∫Ìƒﬁ∫∏',11900,0,'∆Àƒ‹(M)2+≈∫ªÍ¿Ω∑·(M)2',3,'1575539272966.jpg','th_1575539272966.jpg');
Insert into BISCUIT.STORE (STORE_NUM,STORE_NAME,STORE_PRICE,STORE_SALE,STORE_NOTE,STORE_PACKAGE,STORE_IMG,STORE_THUMBIMG) values (55,'Ω∫∏Ùºº∆Æ',6200,0,'∆Àƒ‹(M)1+≈∫ªÍ¿Ω∑·(M)1',3,'1575539306116.jpg','th_1575539306116.jpg');
Insert into BISCUIT.STORE (STORE_NUM,STORE_NAME,STORE_PRICE,STORE_SALE,STORE_NOTE,STORE_PACKAGE,STORE_IMG,STORE_THUMBIMG) values (56,'∂Û¡ˆƒﬁ∫∏',13900,0,'∆Àƒ‹(L)2+≈∫ªÍ¿Ω∑·(L)2',3,'1575539361324.jpg','th_1575539361324.jpg');
Insert into BISCUIT.STORE (STORE_NUM,STORE_NAME,STORE_PRICE,STORE_SALE,STORE_NOTE,STORE_PACKAGE,STORE_IMG,STORE_THUMBIMG) values (57,'GOURMETƒﬁ∫∏',9900,0,'∞Ì∏ﬁ∆Àƒ‹(L)1+≈∫ªÍ¿Ω∑·(M)2',3,'1575539401931.jpg','th_1575539401931.jpg');
Insert into BISCUIT.STORE (STORE_NUM,STORE_NAME,STORE_PRICE,STORE_SALE,STORE_NOTE,STORE_PACKAGE,STORE_IMG,STORE_THUMBIMG) values (58,'GOURMET¥ı∫Ìƒﬁ∫∏',12400,0,'∞Ì∏ﬁ∆Àƒ‹(M)2+≈∫ªÍ¿Ω∑·(M)2',3,'1575539435467.jpg','th_1575539435467.jpg');

--------------------------------------------------------
--  DDL for Index STORE_STORENUM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BISCUIT"."STORE_STORENUM_PK" ON "BISCUIT"."STORE" ("STORE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STORE
--------------------------------------------------------

  ALTER TABLE "BISCUIT"."STORE" MODIFY ("STORE_PACKAGE" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."STORE" ADD CONSTRAINT "STORE_STORENUM_PK" PRIMARY KEY ("STORE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BISCUIT"."STORE" MODIFY ("STORE_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."STORE" MODIFY ("STORE_NAME" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."STORE" MODIFY ("STORE_SALE" NOT NULL ENABLE);
