--------------------------------------------------------
--  파일이 생성됨 - 화요일-12월-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "BISCUIT"."CART" 
   (	"CART_NUM" NUMBER(8,0), 
	"MEMBER_ID" VARCHAR2(200 BYTE), 
	"STORE_NUM" NUMBER(5,0), 
	"CART_AMOUNT" NUMBER(4,0), 
	"CART_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BISCUIT.CART
SET DEFINE OFF;
Insert into BISCUIT.CART (CART_NUM,MEMBER_ID,STORE_NUM,CART_AMOUNT,CART_DATE) values (248,'admin',78,4,to_date('19/12/24','RR/MM/DD'));
Insert into BISCUIT.CART (CART_NUM,MEMBER_ID,STORE_NUM,CART_AMOUNT,CART_DATE) values (252,'daze123',46,1,to_date('19/12/24','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007263
--------------------------------------------------------

  CREATE UNIQUE INDEX "BISCUIT"."SYS_C007263" ON "BISCUIT"."CART" ("CART_NUM", "MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "BISCUIT"."CART" MODIFY ("CART_DATE" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."CART" MODIFY ("STORE_NUM" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."CART" ADD PRIMARY KEY ("CART_NUM", "MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BISCUIT"."CART" MODIFY ("CART_AMOUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "BISCUIT"."CART" ADD CONSTRAINT "CART_MEMBERID_FK" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "BISCUIT"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BISCUIT"."CART" ADD CONSTRAINT "CART_STORENUM_FK" FOREIGN KEY ("STORE_NUM")
	  REFERENCES "BISCUIT"."STORE" ("STORE_NUM") ON DELETE CASCADE ENABLE;
