--------------------------------------------------------
--  파일이 생성됨 - 화요일-12월-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SEAT
--------------------------------------------------------

  CREATE TABLE "BISCUIT"."SEAT" 
   (	"SEAT_NUM" NUMBER(5,0), 
	"CINEMA_NUM" NUMBER(5,0), 
	"SEAT_NAME" VARCHAR2(20 BYTE), 
	"TIMEINFO_START" VARCHAR2(200 BYTE), 
	"MOVIEINFO_NAME" VARCHAR2(200 BYTE), 
	"TIMEINFO_DATE" VARCHAR2(200 BYTE), 
	"THEATER_NUM" NUMBER(5,0), 
	"MOVIEINFO_NUM" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BISCUIT.SEAT
SET DEFINE OFF;
Insert into BISCUIT.SEAT (SEAT_NUM,CINEMA_NUM,SEAT_NAME,TIMEINFO_START,MOVIEINFO_NAME,TIMEINFO_DATE,THEATER_NUM,MOVIEINFO_NUM) values (6688,1,'D3','17:00','백두산','19/12/24',1,'270');
Insert into BISCUIT.SEAT (SEAT_NUM,CINEMA_NUM,SEAT_NAME,TIMEINFO_START,MOVIEINFO_NAME,TIMEINFO_DATE,THEATER_NUM,MOVIEINFO_NUM) values (6689,1,'D4','17:00','백두산','19/12/24',1,'270');
Insert into BISCUIT.SEAT (SEAT_NUM,CINEMA_NUM,SEAT_NAME,TIMEINFO_START,MOVIEINFO_NAME,TIMEINFO_DATE,THEATER_NUM,MOVIEINFO_NUM) values (6690,1,'D5','17:00','백두산','19/12/24',1,'270');
Insert into BISCUIT.SEAT (SEAT_NUM,CINEMA_NUM,SEAT_NAME,TIMEINFO_START,MOVIEINFO_NAME,TIMEINFO_DATE,THEATER_NUM,MOVIEINFO_NUM) values (6691,1,'D6','17:00','백두산','19/12/24',1,'270');
Insert into BISCUIT.SEAT (SEAT_NUM,CINEMA_NUM,SEAT_NAME,TIMEINFO_START,MOVIEINFO_NAME,TIMEINFO_DATE,THEATER_NUM,MOVIEINFO_NUM) values (6692,1,'D7','17:00','백두산','19/12/24',1,'270');
--------------------------------------------------------
--  DDL for Index SEAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BISCUIT"."SEAT_PK" ON "BISCUIT"."SEAT" ("SEAT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SEAT
--------------------------------------------------------

  ALTER TABLE "BISCUIT"."SEAT" ADD CONSTRAINT "SEAT_PK" PRIMARY KEY ("SEAT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BISCUIT"."SEAT" MODIFY ("SEAT_NUM" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."SEAT" MODIFY ("CINEMA_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SEAT
--------------------------------------------------------

  ALTER TABLE "BISCUIT"."SEAT" ADD CONSTRAINT "SEAT_CINEMANUM_FK" FOREIGN KEY ("CINEMA_NUM")
	  REFERENCES "BISCUIT"."CINEMA" ("CINEMA_NUM") ENABLE;
