--------------------------------------------------------
--  파일이 생성됨 - 화요일-12월-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "BISCUIT"."MEMBER" 
   (	"ID" VARCHAR2(200 BYTE), 
	"PW" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"ADDRESS" VARCHAR2(400 BYTE), 
	"POST" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(200 BYTE), 
	"BIRTH" DATE, 
	"GENDER" VARCHAR2(10 BYTE), 
	"GRADE" NUMBER(1,0), 
	"GRADE_POINT" NUMBER(8,0), 
	"SIGNIN_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BISCUIT.MEMBER
SET DEFINE OFF;
Insert into BISCUIT.MEMBER (ID,PW,NAME,EMAIL,ADDRESS,POST,PHONE,BIRTH,GENDER,GRADE,GRADE_POINT,SIGNIN_DATE) values ('admin','1234','관리자','admin@email.com','서울특별시 마포구','00000','010-0000-0000',to_date('50/01/01','RR/MM/DD'),'F',6,0,to_date('19/11/26','RR/MM/DD'));
Insert into BISCUIT.MEMBER (ID,PW,NAME,EMAIL,ADDRESS,POST,PHONE,BIRTH,GENDER,GRADE,GRADE_POINT,SIGNIN_DATE) values ('Member1','Member1','회원1','member1@email.com','서울특별시 강동구','12345','010-1111-1111',to_date('19/11/20','RR/MM/DD'),'M',5,0,to_date('19/11/26','RR/MM/DD'));
Insert into BISCUIT.MEMBER (ID,PW,NAME,EMAIL,ADDRESS,POST,PHONE,BIRTH,GENDER,GRADE,GRADE_POINT,SIGNIN_DATE) values ('Member2','Member2','회원2','member2@email.com','수원시 영통구','45678','010-2222-2222',to_date('03/01/24','RR/MM/DD'),'M',5,0,to_date('19/11/26','RR/MM/DD'));
Insert into BISCUIT.MEMBER (ID,PW,NAME,EMAIL,ADDRESS,POST,PHONE,BIRTH,GENDER,GRADE,GRADE_POINT,SIGNIN_DATE) values ('Member3','Member3','회원3','member3@email.com','인천광역시 부평구','34567','010-3333-3333',to_date('14/08/18','RR/MM/DD'),'F',5,0,to_date('19/11/26','RR/MM/DD'));
Insert into BISCUIT.MEMBER (ID,PW,NAME,EMAIL,ADDRESS,POST,PHONE,BIRTH,GENDER,GRADE,GRADE_POINT,SIGNIN_DATE) values ('Member5','Member5','회원5','member5@email.com','광주광역시 북구','87654','010-5555-5555',to_date('94/02/02','RR/MM/DD'),'M',5,0,to_date('19/11/26','RR/MM/DD'));
Insert into BISCUIT.MEMBER (ID,PW,NAME,EMAIL,ADDRESS,POST,PHONE,BIRTH,GENDER,GRADE,GRADE_POINT,SIGNIN_DATE) values ('daze123','1234','임윤희123','daze123@hanmail.net','서울 강남구 남부순환로 2907','06281','010-4735-2699',to_date('97/07/10','RR/MM/DD'),'F',4,0,to_date('19/12/11','RR/MM/DD'));

--------------------------------------------------------
--  DDL for Index MEMBER_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BISCUIT"."MEMBER_ID_PK" ON "BISCUIT"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEMBER_EMAIL_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BISCUIT"."MEMBER_EMAIL_UNIQUE" ON "BISCUIT"."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "BISCUIT"."MEMBER" ADD CONSTRAINT "MEMBER_EMAIL_UNIQUE" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BISCUIT"."MEMBER" ADD CONSTRAINT "MEMBER_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BISCUIT"."MEMBER" MODIFY ("SIGNIN_DATE" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."MEMBER" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."MEMBER" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."MEMBER" MODIFY ("PW" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "BISCUIT"."MEMBER" ADD CONSTRAINT "MEMBER_GRADEPOINT_FK" FOREIGN KEY ("GRADE")
	  REFERENCES "BISCUIT"."MEMBER_GRADE" ("GRADE_NUM") ENABLE;
