--------------------------------------------------------
--  파일이 생성됨 - 화요일-12월-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TIMEINFO
--------------------------------------------------------

  CREATE TABLE "BISCUIT"."TIMEINFO" 
   (	"TIMEINFO_NUM" NUMBER(5,0), 
	"THEATER_NUM" NUMBER(5,0), 
	"MOVIEINFO_NUM" NUMBER(5,0), 
	"TIMEINFO_DATE" DATE, 
	"TIMEINFO_START" TIMESTAMP (6), 
	"TIMEINFO_END" TIMESTAMP (6), 
	"CINEMA_NUM" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BISCUIT.TIMEINFO
SET DEFINE OFF;
Insert into BISCUIT.TIMEINFO (TIMEINFO_NUM,THEATER_NUM,MOVIEINFO_NUM,TIMEINFO_DATE,TIMEINFO_START,TIMEINFO_END,CINEMA_NUM) values (13788,174,102,to_date('19/12/26','RR/MM/DD'),to_timestamp('19/12/26 13:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('19/12/26 15:10:00.000000000','RR/MM/DD HH24:MI:SSXFF'),58);
Insert into BISCUIT.TIMEINFO (TIMEINFO_NUM,THEATER_NUM,MOVIEINFO_NUM,TIMEINFO_DATE,TIMEINFO_START,TIMEINFO_END,CINEMA_NUM) values (13789,174,102,to_date('19/12/26','RR/MM/DD'),to_timestamp('19/12/26 16:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('19/12/26 18:10:00.000000000','RR/MM/DD HH24:MI:SSXFF'),58);
Insert into BISCUIT.TIMEINFO (TIMEINFO_NUM,THEATER_NUM,MOVIEINFO_NUM,TIMEINFO_DATE,TIMEINFO_START,TIMEINFO_END,CINEMA_NUM) values (13790,174,102,to_date('19/12/26','RR/MM/DD'),to_timestamp('19/12/26 19:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('19/12/26 21:10:00.000000000','RR/MM/DD HH24:MI:SSXFF'),58);
Insert into BISCUIT.TIMEINFO (TIMEINFO_NUM,THEATER_NUM,MOVIEINFO_NUM,TIMEINFO_DATE,TIMEINFO_START,TIMEINFO_END,CINEMA_NUM) values (13791,174,102,to_date('19/12/26','RR/MM/DD'),to_timestamp('19/12/26 22:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('19/12/27 00:10:00.000000000','RR/MM/DD HH24:MI:SSXFF'),58);
Insert into BISCUIT.TIMEINFO (TIMEINFO_NUM,THEATER_NUM,MOVIEINFO_NUM,TIMEINFO_DATE,TIMEINFO_START,TIMEINFO_END,CINEMA_NUM) values (13792,175,270,to_date('19/12/26','RR/MM/DD'),to_timestamp('19/12/26 08:00:00.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('19/12/26 10:08:00.000000000','RR/MM/DD HH24:MI:SSXFF'),59);
--------------------------------------------------------
--  DDL for Index TIMEINFO_TIMEINFONUM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BISCUIT"."TIMEINFO_TIMEINFONUM_PK" ON "BISCUIT"."TIMEINFO" ("TIMEINFO_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TIMEINFO
--------------------------------------------------------

  ALTER TABLE "BISCUIT"."TIMEINFO" ADD CONSTRAINT "TIMEINFO_TIMEINFONUM_PK" PRIMARY KEY ("TIMEINFO_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BISCUIT"."TIMEINFO" MODIFY ("TIMEINFO_END" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."TIMEINFO" MODIFY ("TIMEINFO_START" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."TIMEINFO" MODIFY ("TIMEINFO_DATE" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."TIMEINFO" MODIFY ("MOVIEINFO_NUM" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."TIMEINFO" MODIFY ("THEATER_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TIMEINFO
--------------------------------------------------------

  ALTER TABLE "BISCUIT"."TIMEINFO" ADD CONSTRAINT "TIMEINFO_MOVIEINFO_FK" FOREIGN KEY ("MOVIEINFO_NUM")
	  REFERENCES "BISCUIT"."MOVIEINFO" ("MOVIEINFO_NUM") ENABLE;
  ALTER TABLE "BISCUIT"."TIMEINFO" ADD CONSTRAINT "TIMEINFO_THEATERNUM_FK" FOREIGN KEY ("THEATER_NUM")
	  REFERENCES "BISCUIT"."THEATER" ("THEATER_NUM") ENABLE;
