--------------------------------------------------------
--  파일이 생성됨 - 화요일-12월-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER_GRADE
--------------------------------------------------------

  CREATE TABLE "BISCUIT"."MEMBER_GRADE" 
   (	"GRADE_NUM" NUMBER(1,0), 
	"GRADE_NAME" VARCHAR2(10 BYTE), 
	"MIN_POINT" NUMBER(8,0), 
	"MAX_POINT" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BISCUIT.MEMBER_GRADE
SET DEFINE OFF;
Insert into BISCUIT.MEMBER_GRADE (GRADE_NUM,GRADE_NAME,MIN_POINT,MAX_POINT) values (1,'VIP',50000,99999999);
Insert into BISCUIT.MEMBER_GRADE (GRADE_NUM,GRADE_NAME,MIN_POINT,MAX_POINT) values (2,'GOLD',30000,49999);
Insert into BISCUIT.MEMBER_GRADE (GRADE_NUM,GRADE_NAME,MIN_POINT,MAX_POINT) values (3,'SILVER',10000,29999);
Insert into BISCUIT.MEMBER_GRADE (GRADE_NUM,GRADE_NAME,MIN_POINT,MAX_POINT) values (4,'GREEN',1,9999);
Insert into BISCUIT.MEMBER_GRADE (GRADE_NUM,GRADE_NAME,MIN_POINT,MAX_POINT) values (5,'WELCOME',0,0);
Insert into BISCUIT.MEMBER_GRADE (GRADE_NUM,GRADE_NAME,MIN_POINT,MAX_POINT) values (6,'ADMIN',-1000000,-1);
--------------------------------------------------------
--  DDL for Index GRADE_NUM_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "BISCUIT"."GRADE_NUM_MEMBER" ON "BISCUIT"."MEMBER_GRADE" ("GRADE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_GRADE
--------------------------------------------------------

  ALTER TABLE "BISCUIT"."MEMBER_GRADE" MODIFY ("MAX_POINT" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."MEMBER_GRADE" MODIFY ("MIN_POINT" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."MEMBER_GRADE" MODIFY ("GRADE_NAME" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."MEMBER_GRADE" ADD CONSTRAINT "GRADE_NUM_MEMBER" PRIMARY KEY ("GRADE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
