--------------------------------------------------------
--  파일이 생성됨 - 화요일-12월-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CINEMA
--------------------------------------------------------

  CREATE TABLE "BISCUIT"."CINEMA" 
   (	"CINEMA_NUM" NUMBER(5,0), 
	"CINEMA_LOC" VARCHAR2(200 BYTE), 
	"CINEMA_NAME" VARCHAR2(200 BYTE), 
	"CINEMA_ADD" VARCHAR2(200 BYTE), 
	"CINEMA_TEL" VARCHAR2(200 BYTE) DEFAULT 1544-1122, 
	"CINEMA_LOCNUM" NUMBER(2,0), 
	"CINEMA_IMAGE" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BISCUIT"."CINEMA"."CINEMA_NUM" IS '극장코드';
   COMMENT ON COLUMN "BISCUIT"."CINEMA"."CINEMA_LOC" IS '지역';
   COMMENT ON COLUMN "BISCUIT"."CINEMA"."CINEMA_NAME" IS '극장명';
   COMMENT ON COLUMN "BISCUIT"."CINEMA"."CINEMA_ADD" IS '주소';
   COMMENT ON COLUMN "BISCUIT"."CINEMA"."CINEMA_TEL" IS '전화번호';
REM INSERTING into BISCUIT.CINEMA
SET DEFINE OFF;
Insert into BISCUIT.CINEMA (CINEMA_NUM,CINEMA_LOC,CINEMA_NAME,CINEMA_ADD,CINEMA_TEL,CINEMA_LOCNUM,CINEMA_IMAGE) values (1,'서울','강남','서울특별시 강남구 강남대로 438','1544-1122',1,'http://img.cgv.co.kr/Theater/Theater/2014/1211/CGVgangnam.jpg');
Insert into BISCUIT.CINEMA (CINEMA_NUM,CINEMA_LOC,CINEMA_NAME,CINEMA_ADD,CINEMA_TEL,CINEMA_LOCNUM,CINEMA_IMAGE) values (2,'서울','강변','서울특별시 광진구 광나루로56길 85','1544-1122',1,'http://img.cgv.co.kr/Theater/Theater/2019/0107/15468415578940.png');
Insert into BISCUIT.CINEMA (CINEMA_NUM,CINEMA_LOC,CINEMA_NAME,CINEMA_ADD,CINEMA_TEL,CINEMA_LOCNUM,CINEMA_IMAGE) values (3,'서울','대학로','서울특별시 종로구 대명길','1544-1122',1,'http://img.cgv.co.kr/Theater/Theater/2015/1027/%EB%8C%80%ED%95%99%EB%A1%9C%EB%AC%B8%ED%99%94%EA%B7%B9%EC%9E%A501.jpg');
Insert into BISCUIT.CINEMA (CINEMA_NUM,CINEMA_LOC,CINEMA_NAME,CINEMA_ADD,CINEMA_TEL,CINEMA_LOCNUM,CINEMA_IMAGE) values (4,'서울','동대문','서울특별시 중구 장충단로 13길 20 현대시티아울렛 11층','1544-1122',1,'http://img.cgv.co.kr/Theater/Theater/2017/1218/15135627350570.jpg');
Insert into BISCUIT.CINEMA (CINEMA_NUM,CINEMA_LOC,CINEMA_NAME,CINEMA_ADD,CINEMA_TEL,CINEMA_LOCNUM,CINEMA_IMAGE) values (5,'서울','등촌','서울특별시 강서구 공항대로45길 63','1544-1122',1,'http://img.cgv.co.kr/Theater/Theater/2019/0411/15549505447290.jpg');
Insert into BISCUIT.CINEMA (CINEMA_NUM,CINEMA_LOC,CINEMA_NAME,CINEMA_ADD,CINEMA_TEL,CINEMA_LOCNUM,CINEMA_IMAGE) values (15,'경기','경기광주','경기도 광주시 중앙로 89','1544-1122',2,'http://img.cgv.co.kr/Theater/Theater/2018/0309/15205836456080.jpg');
Insert into BISCUIT.CINEMA (CINEMA_NUM,CINEMA_LOC,CINEMA_NAME,CINEMA_ADD,CINEMA_TEL,CINEMA_LOCNUM,CINEMA_IMAGE) values (16,'경기','광교상현','경기도 용인시 수지구 상현동 1116-4 W스퀘어','1544-1122',2,'http://img.cgv.co.kr/Theater/Theater/2018/0817/15344706880530.jpg');
Insert into BISCUIT.CINEMA (CINEMA_NUM,CINEMA_LOC,CINEMA_NAME,CINEMA_ADD,CINEMA_TEL,CINEMA_LOCNUM,CINEMA_IMAGE) values (17,'경기','구리','경기도 구리시 경춘로 243','1544-1122',2,'http://img.cgv.co.kr/Theater/Theater/2017/0413/14920645701080.jpg');
Insert into BISCUIT.CINEMA (CINEMA_NUM,CINEMA_LOC,CINEMA_NAME,CINEMA_ADD,CINEMA_TEL,CINEMA_LOCNUM,CINEMA_IMAGE) values (18,'경기','김포','경기도 김포시 사우중로 52','1544-1122',2,'http://img.cgv.co.kr/Theater/Theater/2016/0411/gimpo.jpg');
Insert into BISCUIT.CINEMA (CINEMA_NUM,CINEMA_LOC,CINEMA_NAME,CINEMA_ADD,CINEMA_TEL,CINEMA_LOCNUM,CINEMA_IMAGE) values (19,'경기','동탄','경기도 화성시 동탄중앙로 220','1544-1122',2,'http://img.cgv.co.kr/Theater/Theater/2014/1211/cgvdongtan.jpg');

--------------------------------------------------------
--  DDL for Index CINEMA_CINEMANUM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BISCUIT"."CINEMA_CINEMANUM_PK" ON "BISCUIT"."CINEMA" ("CINEMA_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CINEMA
--------------------------------------------------------

  ALTER TABLE "BISCUIT"."CINEMA" MODIFY ("CINEMA_LOCNUM" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."CINEMA" MODIFY ("CINEMA_TEL" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."CINEMA" MODIFY ("CINEMA_ADD" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."CINEMA" MODIFY ("CINEMA_NAME" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."CINEMA" MODIFY ("CINEMA_LOC" NOT NULL ENABLE);
  ALTER TABLE "BISCUIT"."CINEMA" ADD CONSTRAINT "CINEMA_CINEMANUM_PK" PRIMARY KEY ("CINEMA_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
